// File generated by Antigravity.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSI07_KHizsXPBh7YZ2bLq7py_4GaIyfg',
    appId: '1:925917165008:web:007dfbcc4dbfd9238335d5',
    messagingSenderId: '925917165008',
    projectId: 'islam-home-official',
    authDomain: 'islam-home-official.firebaseapp.com',
    storageBucket: 'islam-home-official.firebasestorage.app',
    measurementId: 'G-3JLNXTT3XQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtC-2O7J1EpI5ymbb78UzU4CBsOVqaqpI',
    appId: '1:925917165008:android:96727fa2ca398c778335d5',
    messagingSenderId: '925917165008',
    projectId: 'islam-home-official',
    storageBucket: 'islam-home-official.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjuU4Ap3XsTO52w50pIA3uEFmlmhY7huc',
    appId: '1:925917165008:ios:383595aabd26f0a58335d5',
    messagingSenderId: '925917165008',
    projectId: 'islam-home-official',
    storageBucket: 'islam-home-official.firebasestorage.app',
    iosBundleId: 'com.islamHome.app',
  );
}
